apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-nginx-conf
  namespace: app-mtls
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8443 ssl;
        # Server cert/key (from hello-tls secret)
        ssl_certificate     /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;

        # Require and verify client cert against our CA
        ssl_client_certificate /etc/nginx/ca/ca.crt;
        ssl_verify_client on;
        ssl_verify_depth 2;

        # Reasonable defaults
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
          default_type text/plain;
          return 200 "hello, mTLS world\n";
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: app-mtls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: tls
          mountPath: /etc/nginx/tls
          readOnly: true
        - name: ca
          mountPath: /etc/nginx/ca
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: hello-nginx-conf
      - name: tls
        secret:
          secretName: hello-tls
      - name: ca
        secret:
          secretName: hello-ca
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: app-mtls
spec:
  selector:
    app: hello
  ports:
  - name: https
    port: 8443
    targetPort: https
    protocol: TCP
    # ClusterIP service; use a test pod to curl it
